import "./globals.css";
import { Inter } from "next/font/google";
import DashboardPage from "./dashboard/page";
import Header from "./components/Header";
import DataProvider from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Imalipay",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex  bg-[#F7F7F7] h-screen">
					<DashboardPage />
					<div className=" bg-[#F7F7F7] h-screen w-full overflow-auto relative">
						<Header />
						<DataProvider>{children}</DataProvider>
					</div>
				</div>
			</body>
		</html>
	);
}
